services:
  redis:
    image: redis:7-alpine
    container_name: rac_redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: rac_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
